version: '3.7'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - static_data:/app/staticfiles
      - "./dist/media:/app/media"
    depends_on:
      - db
  
  db:
    image: postgres
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    env_file:
      - ./.env

volumes:
  static_data:
  database: